# Generated by Django 2.2.2 on 2019-06-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
