# Generated by Django 2.2.1 on 2019-05-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_auto_20190527_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='no_photo.jpg', upload_to='profile_pics'),
        ),
    ]
