# Generated by Django 2.2.1 on 2019-06-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/no_photo.jpg', upload_to='profile_pics/'),
        ),
    ]
